### ISSUE TITLE
Feedback above app save

### ISSUE THREAD

**Issue by ivanagas** [PostHog/feedback-app#4]
Feedback button showing over app config save. Don't know if this is more of a PostHog or feedback app problem. 

![Screen Shot 2022-10-20 at 12 44 53 PM](https://user-images.githubusercontent.com/34755028/197043441-0aa13cab-34e1-4c7e-8e01-efb25e505fad.png)

**Comment by lharries** [comment]
Thanks! I've removed the icon and instead we are adding a button in the topbar
