### ISSUE TITLE
Feedback app has disappeared from Posthog

### ISSUE THREAD

**Issue by mattf96s** [PostHog/feedback-app#7]
Hi

I can no longer see or access the Feedback app from within Posthog (cloud version). 
Has it been removed?

Thanks

**Comment by mariusandra** [comment]
Hey @mattf96s , apologies for that. We were having trouble upgrading the app (we found a [fix](https://github.com/PostHog/posthog/pull/12420#pullrequestreview-1154821395)), but in the process this app got reinstalled. I have now re-enabled it for all cloud users. You will unfortunately have to configure it up again, sorry about that :(. Any captured feedback will still be there, as that's captured just as posthog events.

Excluding this incident, I'm actually very curious to hear about your experience with this app. We haven't really promoted it yet, so I'm curious to hear how did you come across it, and if it has been useful in any way.
